// ハイクラス人材データ（すべて架空のサンプルプロフィールです / All profiles are fictional samples）
// 実在の人物とは一切関係ありません。デモ・プロトタイプ用のダミーデータです。
window.CANDIDATES = [
  {
    id: "C001", name: "佐藤 玲奈", title: "VP of Engineering",
    role: "engineering", seniority: "vp", years: 16, salaryMin: 1600, salaryMax: 2200,
    industries: ["saas", "fintech"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 45,
    skills: ["組織マネジメント", "SRE", "Go", "Kubernetes", "スケーリング", "採用"],
    summary: "急成長SaaSで開発組織を8名→60名に拡大。SRE文化の定着と可用性99.99%を実現。",
    availability: "active", // active: 積極的に検討 / passive: 良い話があれば
  },
  {
    id: "C002", name: "田中 健太郎", title: "CFO",
    role: "finance", seniority: "cxo", years: 22, salaryMin: 2200, salaryMax: 3500,
    industries: ["manufacturing", "fintech"], locations: ["tokyo", "osaka"],
    languages: ["ja", "en"], management: 30,
    skills: ["IPO準備", "資本政策", "M&A", "管理会計", "IR", "内部統制"],
    summary: "製造業スタートアップのCFOとしてマザーズ上場を主導。VCラウンド累計80億円を調達。",
    availability: "passive",
  },
  {
    id: "C003", name: "鈴木 美咲", title: "Chief Product Officer",
    role: "product", seniority: "cxo", years: 14, salaryMin: 1800, salaryMax: 2600,
    industries: ["saas", "ecommerce"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 25,
    skills: ["プロダクト戦略", "PLG", "データ分析", "ロードマップ", "UXリサーチ", "GTM"],
    summary: "BtoB SaaSのCPOとしてPLGモデルへ転換。ARRを3年で5倍に成長させた。",
    availability: "active",
  },
  {
    id: "C004", name: "高橋 亮", title: "Engineering Manager",
    role: "engineering", seniority: "manager", years: 11, salaryMin: 1100, salaryMax: 1500,
    industries: ["saas", "gaming"], locations: ["remote", "fukuoka"],
    languages: ["ja"], management: 12,
    skills: ["TypeScript", "React", "AWS", "チームビルディング", "アジャイル"],
    summary: "フルリモートの開発チームを率いる。ゲーム/SaaS双方でのプロダクト開発経験。",
    availability: "passive",
  },
  {
    id: "C005", name: "伊藤 さくら", title: "VP of Sales",
    role: "sales", seniority: "vp", years: 18, salaryMin: 1500, salaryMax: 2400,
    industries: ["saas", "consulting"], locations: ["tokyo"],
    languages: ["ja", "en"], management: 40,
    skills: ["エンタープライズ営業", "The Model", "パートナー戦略", "予実管理", "組織構築"],
    summary: "外資系SaaSの日本法人でVP of Salesを歴任。エンタープライズ売上を年200%成長。",
    availability: "active",
  },
  {
    id: "C006", name: "渡辺 大輔", title: "CTO",
    role: "engineering", seniority: "cxo", years: 20, salaryMin: 2000, salaryMax: 3000,
    industries: ["fintech", "saas"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 80,
    skills: ["アーキテクチャ", "セキュリティ", "Rust", "組織マネジメント", "技術戦略", "採用"],
    summary: "フィンテック企業のCTOとして100名規模の技術組織を統括。ゼロダウンタイム決済基盤を構築。",
    availability: "passive",
  },
  {
    id: "C007", name: "山本 由紀", title: "Head of Marketing",
    role: "marketing", seniority: "director", years: 13, salaryMin: 1200, salaryMax: 1800,
    industries: ["ecommerce", "saas"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 15,
    skills: ["ブランド戦略", "デジタルマーケ", "CRM", "コンテンツ", "グロース"],
    summary: "D2Cブランドのマーケ責任者。CAC 40%削減とLTV倍増を同時に達成。",
    availability: "active",
  },
  {
    id: "C008", name: "中村 翔太", title: "Staff Software Engineer",
    role: "engineering", seniority: "director", years: 12, salaryMin: 1300, salaryMax: 1900,
    industries: ["saas", "fintech"], locations: ["remote"],
    languages: ["ja", "en"], management: 0,
    skills: ["分散システム", "Go", "Kubernetes", "gRPC", "パフォーマンス最適化", "技術リード"],
    summary: "IC（個人貢献者）トラックのStaffエンジニア。決済系の分散システム設計をリード。",
    availability: "passive",
  },
  {
    id: "C009", name: "小林 明日香", title: "VP of People",
    role: "hr", seniority: "vp", years: 17, salaryMin: 1400, salaryMax: 2000,
    industries: ["saas", "consulting"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 20,
    skills: ["組織開発", "人事制度設計", "採用戦略", "カルチャー", "エンゲージメント"],
    summary: "急成長企業のHR責任者として組織を50名→300名に拡大。等級・評価制度をゼロから構築。",
    availability: "active",
  },
  {
    id: "C010", name: "加藤 誠", title: "COO",
    role: "operations", seniority: "cxo", years: 24, salaryMin: 2400, salaryMax: 4000,
    industries: ["manufacturing", "ecommerce"], locations: ["tokyo", "osaka"],
    languages: ["ja", "en"], management: 120,
    skills: ["事業戦略", "オペレーション改革", "PMI", "サプライチェーン", "P&L管理"],
    summary: "上場企業のCOOとして全社オペレーションを統括。買収後統合(PMI)を複数成功に導く。",
    availability: "passive",
  },
  {
    id: "C011", name: "吉田 千尋", title: "Head of Data Science",
    role: "data", seniority: "director", years: 12, salaryMin: 1400, salaryMax: 2000,
    industries: ["fintech", "saas"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 10,
    skills: ["機械学習", "MLOps", "Python", "レコメンド", "データ基盤", "統計"],
    summary: "データサイエンス組織の立ち上げから信用スコアリングモデルの本番運用まで一気通貫で推進。",
    availability: "active",
  },
  {
    id: "C012", name: "松本 拓也", title: "VP of Product",
    role: "product", seniority: "vp", years: 15, salaryMin: 1600, salaryMax: 2300,
    industries: ["gaming", "saas"], locations: ["tokyo", "remote"],
    languages: ["ja"], management: 22,
    skills: ["プロダクトマネジメント", "PMF", "グロース", "A/Bテスト", "ロードマップ"],
    summary: "複数の0→1プロダクトを立ち上げPMFを達成。ゲームとSaaSの両領域を経験。",
    availability: "passive",
  },
  {
    id: "C013", name: "井上 真央", title: "General Counsel",
    role: "legal", seniority: "cxo", years: 19, salaryMin: 1800, salaryMax: 2800,
    industries: ["fintech", "saas"], locations: ["tokyo"],
    languages: ["ja", "en"], management: 8,
    skills: ["コーポレート法務", "コンプライアンス", "規制対応", "契約", "ガバナンス"],
    summary: "フィンテック企業の法務責任者。金融規制対応とライセンス取得を主導。",
    availability: "active",
  },
  {
    id: "C014", name: "木村 涼介", title: "Head of Security",
    role: "engineering", seniority: "director", years: 14, salaryMin: 1500, salaryMax: 2100,
    industries: ["fintech", "saas"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 9,
    skills: ["セキュリティ", "脆弱性診断", "ISMS", "SOC2", "インシデント対応", "ゼロトラスト"],
    summary: "金融系サービスのセキュリティ責任者。SOC2 Type II取得とゼロトラスト移行を完遂。",
    availability: "passive",
  },
  {
    id: "C015", name: "林 香織", title: "VP of Customer Success",
    role: "sales", seniority: "vp", years: 13, salaryMin: 1300, salaryMax: 1900,
    industries: ["saas", "consulting"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 28,
    skills: ["カスタマーサクセス", "解約率改善", "オンボーディング", "アップセル", "組織構築"],
    summary: "SaaSのCS組織を統括しネットレベニューリテンションを120%超に改善。",
    availability: "active",
  },
  {
    id: "C016", name: "清水 健", title: "Principal Engineer",
    role: "engineering", seniority: "director", years: 18, salaryMin: 1600, salaryMax: 2300,
    industries: ["saas", "manufacturing"], locations: ["osaka", "remote"],
    languages: ["ja"], management: 0,
    skills: ["組み込み", "C++", "Rust", "リアルタイム処理", "アーキテクチャ", "技術リード"],
    summary: "IoT/組み込み領域のプリンシパルエンジニア。ハードとソフトを横断する設計に強み。",
    availability: "passive",
  },
  {
    id: "C017", name: "森 彩香", title: "Chief Marketing Officer",
    role: "marketing", seniority: "cxo", years: 20, salaryMin: 1900, salaryMax: 2800,
    industries: ["ecommerce", "consulting"], locations: ["tokyo"],
    languages: ["ja", "en"], management: 35,
    skills: ["ブランド戦略", "マーケティング組織", "PR", "グローバル展開", "事業開発"],
    summary: "グローバルD2CブランドのCMO。海外3ヶ国への市場参入を成功させた。",
    availability: "active",
  },
  {
    id: "C018", name: "池田 悠真", title: "Director of Engineering",
    role: "engineering", seniority: "director", years: 13, salaryMin: 1400, salaryMax: 1900,
    industries: ["saas", "fintech"], locations: ["tokyo", "remote"],
    languages: ["ja", "en"], management: 24,
    skills: ["組織マネジメント", "TypeScript", "AWS", "プラットフォーム", "採用", "アジャイル"],
    summary: "プラットフォーム部門のディレクター。複数チーム横断の開発生産性を大幅に改善。",
    availability: "passive",
  },
];
